### ISSUE TITLE
Fix Requirement.txt

### ISSUE THREAD

**Issue by Vishwaak** [Fireboltz/Psychic-CCTV#8]
# Summary

There are a lot of redundant modules in the requirement.txt. The one not necessary for the projects can be removed.

**Comment by saisiddhant12** [comment]
can I take this up ?

**Comment by Vishwaak** [comment]
Yeah feel free, to work on this issue :smile:

**Comment by ShehzadAhm** [comment]
Hi @saisiddhant12, can I work on this issue?

**Comment by ShehzadAhm** [comment]
Hi @Vishwaak, can I work on this issue?

**Comment by saisiddhant12** [comment]
@ShehzadAhm am working on it, feel free to look at other issue on pyqt

**Comment by ShehzadAhm** [comment]
@saisiddhant12 Ok no problem.

**Comment by saisiddhant12** [comment]
@Vishwaak 
I see there is a problem in usual installation of pyaudio for python 3.8, do you want to create a separate issue for that ?

**Comment by Vishwaak** [comment]
It would be better if we can stick around with Python 3.7 for the project as there are few other modules that currently don't have support for the Python 3.8.

**Comment by saisiddhant12** [comment]
Got it, I will validate the environment using python 3.7

**Comment by saisiddhant12** [comment]
@Vishwaak 
I believe packages like tkinter cant be installed using pypy packages rather we need to install on the platform's package manager,

**Comment by saisiddhant12** [comment]
@Vishwaak 
I was able to create a PR for the requirements and the issue is mentioned over here 
https://github.com/Fireboltz/Psychic-CCTV/pull/9

The part where I had to use package mnager instead of pip are as follows
tkinter: 
python-dev
portaudio19-dev
